// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20260909203052_FixLedgerNullableFK")]
    partial class FixLedgerNullableFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditoria_Log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalle_json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entidad_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Auditoria_log");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("saldo_disponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("saldo_retenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("saldo_total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("Billetera");

                    b.HasData(
                        new
                        {
                            id = 1,
                            saldo_disponible = 0m,
                            saldo_retenido = 0m,
                            saldo_total = 100000m,
                            usuario_id = 1,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 2,
                            saldo_disponible = 105000m,
                            saldo_retenido = 45000m,
                            saldo_total = 150000m,
                            usuario_id = 2,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 3,
                            saldo_disponible = 200000m,
                            saldo_retenido = 0m,
                            saldo_total = 200000m,
                            usuario_id = 3,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 4,
                            saldo_disponible = 0m,
                            saldo_retenido = 0m,
                            saldo_total = 500m,
                            usuario_id = 4,
                            version = new byte[0]
                        });
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Tecnología",
                            url_icono = ""
                        },
                        new
                        {
                            id = 2,
                            nombre = "Coleccionables",
                            url_icono = ""
                        },
                        new
                        {
                            id = 3,
                            nombre = "Indumentaria",
                            url_icono = ""
                        },
                        new
                        {
                            id = 4,
                            nombre = "Vehículos",
                            url_icono = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Compradorid")
                        .HasColumnType("int");

                    b.Property<int?>("Subastaid")
                        .HasColumnType("int");

                    b.Property<int>("comprador_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_puja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("subasta_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Compradorid");

                    b.HasIndex("Subastaid");

                    b.ToTable("Puja");

                    b.HasData(
                        new
                        {
                            id = 1,
                            comprador_id = 4,
                            fecha_puja = new DateTime(2026, 9, 9, 17, 35, 52, 564, DateTimeKind.Local).AddTicks(304),
                            monto = 500m,
                            subasta_id = 1
                        },
                        new
                        {
                            id = 3,
                            comprador_id = 2,
                            fecha_puja = new DateTime(2026, 9, 9, 17, 40, 52, 564, DateTimeKind.Local).AddTicks(323),
                            monto = 45000m,
                            subasta_id = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Categoriaid")
                        .HasColumnType("int");

                    b.Property<int?>("Vendedorid")
                        .HasColumnType("int");

                    b.Property<int>("categoria_id")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("incremento_minimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("precio_base")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vendedor_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("id");

                    b.HasIndex("Categoriaid");

                    b.HasIndex("Vendedorid");

                    b.ToTable("Subasta");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoria_id = 1,
                            descripcion = "Celular Samsung",
                            estado = "ACTIVA",
                            fecha_fin = new DateTime(2026, 9, 9, 18, 0, 52, 564, DateTimeKind.Local).AddTicks(351),
                            fecha_inicio = new DateTime(2026, 9, 9, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(350),
                            incremento_minimo = 1000m,
                            precio_base = 30000m,
                            titulo = "Celular",
                            url_imagen = "",
                            vendedor_id = 1,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 2,
                            categoria_id = 2,
                            descripcion = "Figura de acción de colección",
                            estado = "ACTIVA",
                            fecha_fin = new DateTime(2026, 9, 9, 17, 31, 52, 564, DateTimeKind.Local).AddTicks(354),
                            fecha_inicio = new DateTime(2026, 9, 9, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(354),
                            incremento_minimo = 500m,
                            precio_base = 5000m,
                            titulo = "Figura de acción",
                            url_imagen = "",
                            vendedor_id = 1,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 3,
                            categoria_id = 3,
                            descripcion = "Camiseta de algodón",
                            estado = "PROGRAMADA",
                            fecha_fin = new DateTime(2026, 9, 9, 17, 31, 52, 564, DateTimeKind.Local).AddTicks(360),
                            fecha_inicio = new DateTime(2026, 9, 10, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(357),
                            incremento_minimo = 1000m,
                            precio_base = 2000m,
                            titulo = "Camiseta",
                            url_imagen = "",
                            vendedor_id = 1,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 4,
                            categoria_id = 4,
                            descripcion = "Bicicleta de montaña",
                            estado = "ACTIVA",
                            fecha_fin = new DateTime(2026, 9, 5, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(363),
                            fecha_inicio = new DateTime(2026, 9, 2, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(362),
                            incremento_minimo = 1000m,
                            precio_base = 10000m,
                            titulo = "Bicicleta",
                            url_imagen = "",
                            vendedor_id = 1,
                            version = new byte[0]
                        },
                        new
                        {
                            id = 5,
                            categoria_id = 1,
                            descripcion = "Tablet de última generación",
                            estado = "ACTIVA",
                            fecha_fin = new DateTime(2026, 9, 8, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(366),
                            fecha_inicio = new DateTime(2026, 9, 2, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(365),
                            incremento_minimo = 1500m,
                            precio_base = 25000m,
                            titulo = "Tablet",
                            url_imagen = "",
                            vendedor_id = 1,
                            version = new byte[0]
                        });
                });

            modelBuilder.Entity("Domain.Entities.Transaccion_Ledger", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Billeteraid")
                        .HasColumnType("int");

                    b.Property<int>("billetera_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("subasta_id")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Billeteraid");

                    b.HasIndex("billetera_id");

                    b.HasIndex("subasta_id");

                    b.ToTable("Transaccion_Ledgers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            billetera_id = 2,
                            fecha = new DateTime(2026, 8, 30, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(395),
                            monto = 150000m,
                            tipo = "DEPOSITO"
                        },
                        new
                        {
                            id = 2,
                            billetera_id = 3,
                            fecha = new DateTime(2026, 8, 30, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(434),
                            monto = 200000m,
                            tipo = "DEPOSITO"
                        },
                        new
                        {
                            id = 3,
                            billetera_id = 4,
                            fecha = new DateTime(2026, 8, 30, 17, 30, 52, 564, DateTimeKind.Local).AddTicks(435),
                            monto = 500m,
                            tipo = "DEPOSITO"
                        },
                        new
                        {
                            id = 4,
                            billetera_id = 2,
                            fecha = new DateTime(2026, 9, 9, 17, 40, 52, 564, DateTimeKind.Local).AddTicks(437),
                            monto = 45000m,
                            subasta_id = 1,
                            tipo = "RETENCION"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "vendedor@test.com",
                            nombre = "Creador de publicaciones",
                            password_hash = "",
                            rol = ""
                        },
                        new
                        {
                            id = 2,
                            email = "comprador1@test.com",
                            nombre = "Postor líder",
                            password_hash = "",
                            rol = ""
                        },
                        new
                        {
                            id = 3,
                            email = "comprador2@test.com",
                            nombre = "Postor habilitado",
                            password_hash = "",
                            rol = ""
                        },
                        new
                        {
                            id = 4,
                            email = "sinfondos@test.com",
                            nombre = "Sin saldo",
                            password_hash = "",
                            rol = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.Auditoria_Log", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("Domain.Entities.Billetera", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Puja", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("Compradorid");

                    b.HasOne("Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("Subastaid");

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("Categoriaid");

                    b.HasOne("Domain.Entities.Usuario", "Vendedor")
                        .WithMany("Subastas")
                        .HasForeignKey("Vendedorid");

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Domain.Entities.Transaccion_Ledger", b =>
                {
                    b.HasOne("Domain.Entities.Billetera", null)
                        .WithMany("Transacciones")
                        .HasForeignKey("Billeteraid");

                    b.HasOne("Domain.Entities.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("billetera_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("subasta_id");

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
