<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UseCases\Auditoria_log\Commands\" />
    <Folder Include="UseCases\Auditoria_log\Handlers\" />
    <Folder Include="UseCases\Auditoria_log\Queries\" />
    <Folder Include="UseCases\Categoria\Commands\" />
    <Folder Include="UseCases\Categoria\Handlers\" />
    <Folder Include="UseCases\Categoria\Queries\" />
    <Folder Include="UseCases\Puja\Queries\" />
    <Folder Include="UseCases\Transaccion_leadger\Commands\" />
    <Folder Include="UseCases\Transaccion_leadger\Handlers\" />
    <Folder Include="UseCases\Transaccion_leadger\Queries\" />
    <Folder Include="UseCases\Usuario\Commands\" />
    <Folder Include="UseCases\Usuario\Handlers\" />
    <Folder Include="UseCases\Usuario\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
