<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="UseCases\Auditoria_log\" />
    <Folder Include="UseCases\Categoria\" />
    <Folder Include="UseCases\Billetera\" />
    <Folder Include="UseCases\Subasta\Commands\" />
    <Folder Include="UseCases\Subasta\Handlers\" />
    <Folder Include="UseCases\Subasta\Queries\" />
    <Folder Include="UseCases\Transaccion_leadger\" />
    <Folder Include="UseCases\Usuario\" />
    <Folder Include="UseCases\Puja\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
